language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
services:
    - mongodb
    - rabbitmqsd
install:
    - pip install --allow-all-external -r requirements.txt
    - pip install coveralls
script:
    coverage run setup.py test
after_success:
    - coverage combine
    - coveralls
